- name: Add the user 'user'
  user:
    name: '{{ user_name }}'
    password: '{{ "{{ user_password }}" | password_hash("sha512") }}'

- name: Set the user's authorized key
  authorized_key:
    user: '{{ user_name }}'
    key: '{{ lookup("file", "{{ public_key_path }}") }}'
